export const graph = {
  ARN: {
    name: 'Arlanda',
    latitude: '59.651944',
    longitude: '17.918611',
    destinations: ['HAM', 'JFK', 'LAX', 'MLA'],
  },
  MLA: {
    name: 'Luqa',
    latitude: '35.857497',
    longitude: '14.4775',
    destinations: ['AMS', 'BRU', 'HAM', 'ARN'],
  },
  CUN: {
    name: 'Cancun Intl',
    latitude: '21.036528',
    longitude: '-86.877083',
    destinations: ['BOS', 'JFK', 'IND', 'LAX'],
  },
  LAX: {
    name: 'Los Angeles Intl',
    latitude: '33.942536',
    longitude: '-118.408075',
    destinations: ['BOS', 'IND', 'JFK', 'CUN', 'ARN'],
  },
  IND: {
    name: 'Indianapolis Intl',
    latitude: '39.717331',
    longitude: '-86.294383',
    destinations: ['JFK', 'LAX', 'ORD', 'CUN', 'BOS', 'SFO'],
  },
  BOS: {
    name: 'General Edward Lawrence Logan Intl',
    latitude: '42.364347',
    longitude: '-71.005181',
    destinations: ['CUN', 'JFK', 'LAX', 'IND'],
  },
  JFK: {
    name: 'John F Kennedy Intl',
    latitude: '40.639751',
    longitude: '-73.778925',
    destinations: ['BOS', 'CUN', 'IND', 'LAX', 'ARN'],
  },
  CGN: {
    name: 'Koln Bonn',
    latitude: '50.865917',
    longitude: '7.142744',
    destinations: ['ARN', 'HAM', 'TLV', 'AMS'],
  },
  MEX: {
    name: 'Licenciado Benito Juarez Intl',
    latitude: '19.436303',
    longitude: '-99.072097',
    destinations: ['CUN', 'JFK', 'LAX', 'AMS'],
  },
  AMS: {
    name: 'Schiphol',
    latitude: '52.308613',
    longitude: '4.763889',
    destinations: [
      'HAM',
      'ARN',
      'CGN',
      'BOS',
      'JFK',
      'LAX',
      'MLA',
      'BRU',
      'MEX',
    ],
  },
  BRU: {
    name: 'Brussels Natl',
    latitude: '50.901389',
    longitude: '4.484444',
    destinations: ['JFK', 'AMS', 'MLA', 'HAM', 'ARN'],
  },
  HAM: {
    name: 'Hamburg',
    latitude: '53.630389',
    longitude: '9.988228',
    destinations: ['AMS', 'ARN', 'CGN', 'MLA', 'BRU'],
  },
  SFO: {
    name: 'San Francisco Intl',
    latitude: '37.618972',
    longitude: '-122.374889',
    destinations: ['JFK', 'LAX', 'MEX', 'BOS', 'AMS', 'CUN', 'IND'],
  },
  SXF: {
    name: 'Schonefeld',
    latitude: '52.380001',
    longitude: '13.5225',
    destinations: ['TLV', 'ARN', 'AMS', 'BRU'],
  },
  TLV: {
    name: 'Ben Gurion',
    latitude: '32.011389',
    longitude: '34.886667',
    destinations: ['CGN', 'SXF', 'JFK', 'ARN', 'AMS', 'BRU', 'LAX'],
  },
  PIT: {
    name: 'Pittsburgh Intl',
    latitude: '40.491467',
    longitude: '-80.232872',
    destinations: ['BOS', 'JFK', 'LAX', 'CUN', 'SFO'],
  },
  AGP: {
    name: 'Malaga',
    latitude: '36.6749',
    longitude: '-4.499106',
    destinations: ['CGN', 'HAM', 'ARN', 'BRU', 'MAN', 'AMS', 'DME', 'SXF'],
  },
  DME: {
    name: 'Domododevo',
    latitude: '55.408611',
    longitude: '37.906111',
    destinations: ['AGP', 'MLA', 'TLV', 'BRU', 'MAN', 'CGN'],
  },
  MAN: {
    name: 'Manchester',
    latitude: '53.353744',
    longitude: '-2.27495',
    destinations: [
      'CGN',
      'HAM',
      'JFK',
      'CUN',
      'ARN',
      'AGP',
      'AMS',
      'MLA',
      'BRU',
      'DME',
      'SXF',
      'TLV',
    ],
  },
  STL: {
    name: 'Lambert St Louis Intl',
    latitude: '38.748697',
    longitude: '-90.370028',
    destinations: ['LAX', 'PIT', 'JFK', 'CUN', 'SFO', 'BOS'],
  },
  VLC: {
    name: 'Valencia',
    latitude: '39.489314',
    longitude: '-0.481625',
    destinations: ['BRS', 'BRU', 'MAN', 'MRS', 'AMS', 'AGP', 'DME'],
  },
  AUS: {
    name: 'Austin Bergstrom Intl',
    latitude: '30.194528',
    longitude: '-97.669889',
    destinations: ['JFK', 'LAX', 'BOS', 'SFO', 'CUN', 'MEX'],
  },
  BKK: {
    name: 'Suvarnabhumi Intl',
    latitude: '13.681108',
    longitude: '100.747283',
    destinations: ['AMS', 'DME', 'ARN', 'TLV', 'BRU'],
  },
  BRS: {
    name: 'Bristol',
    latitude: '51.382669',
    longitude: '-2.719089',
    destinations: ['AMS', 'HAM', 'AGP', 'MLA', 'VLC', 'BRU', 'SXF'],
  },
  NDR: {
    name: 'El Aroui Airport',
    latitude: '34.9888',
    longitude: '-3.02821',
    destinations: ['AMS', 'BRU', 'CGN', 'MRS'],
  },
  MRS: {
    name: 'Provence',
    latitude: '43.435555',
    longitude: '5.213611',
    destinations: ['AMS', 'TLV', 'AGP', 'MLA', 'NDR', 'VLC', 'BRU'],
  },
  LUX: {
    name: 'Luxembourg',
    latitude: '49.626575',
    longitude: '6.211517',
    destinations: ['AMS', 'AGP', 'ARN', 'MLA', 'VIE'],
  },
  VIE: {
    name: 'Schwechat',
    latitude: '48.110278',
    longitude: '16.569722',
    destinations: [
      'CGN',
      'HAM',
      'AGP',
      'ARN',
      'MLA',
      'VLC',
      'BKK',
      'DME',
      'TLV',
      'AMS',
      'LUX',
      'MAN',
      'BRU',
      'JFK',
      'TUN',
    ],
  },
  TUN: {
    name: 'Carthage',
    latitude: '36.851033',
    longitude: '10.227217',
    destinations: ['CGN', 'MRS', 'AMS', 'BRU', 'DME', 'VIE', 'MLA'],
  },
  TPE: {
    name: 'Taoyuan Intl',
    latitude: '25.077731',
    longitude: '121.232822',
    destinations: ['AMS', 'BKK', 'JFK', 'LAX', 'SFO', 'VIE'],
  },
  OPO: {
    name: 'Porto',
    latitude: '41.248055',
    longitude: '-8.681389',
    destinations: ['AMS', 'BRU', 'MRS', 'VLC', 'LUX'],
  },
  ORD: {
    name: 'Chicago Ohare Intl',
    latitude: '41.978603',
    longitude: '-87.904842',
    destinations: [
      'AUS',
      'BOS',
      'CUN',
      'IND',
      'JFK',
      'LAX',
      'MAN',
      'MEX',
      'PDX',
      'PIT',
      'SFO',
      'STL',
      'AMS',
      'VIE',
      'ARN',
      'BRU',
    ],
  },
  BJX: {
    name: 'Guanajuato Intl',
    latitude: '20.993464',
    longitude: '-101.480847',
    destinations: ['MEX', 'SFO', 'LAX', 'CUN'],
  },
  GLA: {
    name: 'Glasgow',
    latitude: '55.871944',
    longitude: '-4.433056',
    destinations: ['AMS', 'MAN', 'CUN', 'MLA', 'AGP', 'BRS', 'SXF'],
  },
  PDX: {
    name: 'Portland Intl',
    latitude: '45.588722',
    longitude: '-122.5975',
    destinations: ['BOS', 'LAX', 'ORD', 'SFO', 'JFK', 'AMS'],
  },
  KWI: {
    name: 'Kuwait Intl',
    latitude: '29.226567',
    longitude: '47.968928',
    destinations: ['AMS', 'BKK', 'JFK', 'TUN'],
  },
  MAD: {
    name: 'Barajas',
    latitude: '40.493556',
    longitude: '-3.566764',
    destinations: [
      'HAM',
      'BOS',
      'JFK',
      'LAX',
      'ORD',
      'VIE',
      'BRU',
      'CUN',
      'MEX',
      'VLC',
      'MAN',
      'MLA',
      'MRS',
      'OPO',
      'AGP',
      'ARN',
      'DME',
      'TLV',
      'AMS',
      'LUX',
      'BKK',
      'TUN',
      'BRS',
      'SXF',
    ],
  },
  MEM: {
    name: 'Memphis Intl',
    latitude: '35.042417',
    longitude: '-89.976667',
    destinations: ['ORD', 'AUS', 'IND', 'LAX', 'PIT'],
  },
  DUS: {
    name: 'Dusseldorf',
    latitude: '51.289453',
    longitude: '6.766775',
    destinations: [
      'ARN',
      'MAD',
      'JFK',
      'LAX',
      'ORD',
      'AGP',
      'CUN',
      'DME',
      'HAM',
      'TLV',
      'VIE',
      'AMS',
      'MAN',
      'LUX',
      'MLA',
      'GLA',
      'VLC',
      'TUN',
    ],
  },
  NAP: {
    name: 'Capodichino',
    latitude: '40.886033',
    longitude: '14.290781',
    destinations: [
      'CGN',
      'HAM',
      'DUS',
      'AMS',
      'TLV',
      'LUX',
      'VIE',
      'BRU',
      'MAN',
      'SXF',
      'TUN',
    ],
  },
};
